### ISSUE TITLE
TypeScript 2536 error with genTimestampsSchema

### ISSUE THREAD

**Issue by JonnxW** [andreww2012/mongoose-zod#7] opened 2023-05-12 11:06 UTC
Hello,

first of all: Thanks for this great package! I work with mongoose for some years now and started using zod a week ago. I found your package and in general it works pretty well!

I just ran into troubles when trying to transpile an ExpressJS service from TypeScript to JavaScript. The issue is on line 71 of index.d.ts, in the declaration if genTimestampsSchema. I get the following error messages:

```
- Type 'k_2' cannot be used to index type '{ [_ in StringLiteral<CrAt & {}> | StringLiteral<UpAt & {}>]: ZodDefault<ZodDate>; }'
- Type 'k_1' cannot be used to index type 'addQuestionMarks<{ [_ in StringLiteral<CrAt & {}> | StringLiteral<UpAt & {}>]: ZodDefault<ZodDate>; } extends infer T_1 extends ZodRawShape ? { [k in keyof T_1]: { [_ in StringLiteral<...> | StringLiteral<...>]: ZodDefault<...>; }[k]["_output"]; } : never>'.
- Type 'k' cannot be used to index type '{ [_ in StringLiteral<CrAt & {}> | StringLiteral<UpAt & {}>]: ZodDefault<ZodDate>; }'.
- Type 'k_2_1' cannot be used to index type '{ [_ in StringLiteral<CrAt & {}> | StringLiteral<UpAt & {}>]: ZodDefault<ZodDate>; }'.
- Type 'k_3' cannot be used to index type 'addQuestionMarks<{ [_ in StringLiteral<CrAt & {}> | StringLiteral<UpAt & {}>]: ZodDefault<ZodDate>; } extends infer T_4 extends ZodRawShape ? { [k_2 in keyof T_4]: { [_ in StringLiteral<...> | StringLiteral<...>]: ZodDefault<...>; }[k_2]["_input"]; } : never>'.
- Type 'k_2' cannot be used to index type '{ [_ in StringLiteral<CrAt & {}> | StringLiteral<UpAt & {}>]: ZodDefault<ZodDate>; }'.
```

Did this issue occur to you? Do you know what could be the problem? I sticked to the exact dependicies as stated in your package.json. This is how my package.json looks:

```json
{
  "scripts": {
    "build:tsc": "npm-run-all tsc",
    "build:post": "cp package*.json dist && cp .npmrc dist 2>/dev/null || : && cd dist && npm ci --production",
    "build": "npm-run-all build:tsc build:post",
  },
  "dependencies": {
    "dotenv": "^16.0.0",
    "express": "^4.18.1",
    "mongoose-zod": "^0.1.1",
    "pool-ts-node": "^2.9.0",
    "pool-ts-utils": "^1.37.0",
    "zod": "3.19"
  },
  "devDependencies": {
    "@types/chai": "^4.3.1",
    "@types/cors": "^2.8.12",
    "@types/express": "^4.17.13",
    "@types/mocha": "^9.1.1",
    "@types/node": "^16.18.28",
    "@typescript-eslint/eslint-plugin": "^5.24.0",
    "@typescript-eslint/parser": "^5.24.0",
    "chai": "^4.3.6",
    "chai-http": "^4.3.0",
    "cors": "^2.8.5",
    "eslint": "^8.15.0",
    "mocha": "^10.0.0",
    "npm-run-all": "^4.1.5",
    "ts-node": "^10.9.1",
    "typescript": "^4.9.4"
  }
}
```

When I comment line 71 out (and don't use genTimestamsSchema), everything compiles fine. This of course should only be a temporary workaround.

I hope you have some ideas and thank you in advance!

All the best!
Jonathan

**Comment by andreww2012** [comment] 2023-05-15 17:48
Hello @JonnxW, thank you for the kind words.

What version of `mongoose` are you using? It is very important, and I can't see it in the dependencies list you provided. Could you also create a repo with a minimal reproduction so that I can see how are you using this function? Thank you!

**Comment by andreww2012** [comment] 2024-02-23 14:44
I couldn't reproduce the issue: https://stackblitz.com/edit/vitejs-vite-wpft6f?file=index.ts
Please kindly provide the code that produces the error if this is still relevant for you. I'm closing for now.

**Closed by andreww2012** 2024-02-23 14:44 UTC
Labels: Needs reproduction
